Initial <model> evolution document.
WebKit/explainers pull request #77
Opened 2021-09-15 23:49 UTC by weinig

Adds an historical account of `<model>` and proposes possible evolutions.

2021-09-15 23:56 UTC, hober requested changes
This looks great; thanks Sam!

Could you also add a link from the explainer to this document?

2021-09-16 07:45 UTC, tomayac commented on model/HistoryAndEvolution.md
> +user for access to privacy gated feature like the camera and motion data, which
```suggestion
user for access to privacy gated features like the camera and motion data, which
```

2021-09-16 07:45 UTC, tomayac commented on model/HistoryAndEvolution.md
> +existing `<img>`, `<picture>` and `<video>` elements to try to build an element
```suggestion
existing `<img>`, `<picture>`, and `<video>` elements to try to build an element
```

2021-09-16 07:46 UTC, tomayac commented on model/HistoryAndEvolution.md
> +obvious parallel is <svg>, which can be loaded as whole document, or built and
```suggestion
obvious parallel is `<svg>`, which can be loaded as whole document, or built and
```

2021-09-16 07:47 UTC, tomayac commented on model/HistoryAndEvolution.md
> +the 2D page as we have with `<model>`, we will have to define how volumes and
```suggestion
the 2D page as we have with `<model>`), we will have to define how volumes and
```

2021-09-16 07:48 UTC, tomayac commented on model/HistoryAndEvolution.md
> +graphs on the web (three.js](https://threejs.org/), [Babylon JS](https://babylonjs.com/),
```suggestion
graphs on the web [three.js](https://threejs.org/), [Babylon JS](https://babylonjs.com/), 
```

2021-09-16 07:48 UTC, tomayac commented on model/HistoryAndEvolution.md
> +a way to specify that they want to use the browser’s builtin renderer when
```suggestion
a way to specify that they want to use the browser’s built-in renderer when
```

2021-09-16 07:49 UTC, tomayac commented on model/HistoryAndEvolution.md
> +the browsers builtin renderer, as it will come with limitations not present in
```suggestion
the browsers built-in renderer, as it will come with limitations not present in
```

2021-09-16 07:50 UTC, tomayac reviewed
Just a drive-by review. Very interesting to see the perspective and the potential horizon for `model`.

2021-09-16 16:23 UTC, weinig commented
> This looks great; thanks Sam!
> 
> Could you also add a link from the explainer to this document?

Will do.

2021-09-16 16:25 UTC, weinig commented
> Just a drive-by review. Very interesting to see the perspective and the potential horizon for `model`.

Thanks for the edits.

2021-09-16 16:33 UTC, weinig commented
Please let me know if the new version works.

2021-09-16 23:02 UTC, hober approved these changes
Looks great!

2021-09-16 23:02 UTC, merged

2021-09-16 23:07 UTC, smfr commented on model/HistoryAndEvolution.md
> +scale) either in a virtual environment (a white void) or in AR using the devices
device's

2021-09-16 23:07 UTC, smfr commented on model/HistoryAndEvolution.md
> +the browsers built-in renderer, as it will come with limitations not present in
browser's